export const types = {
    // Sync
    FILL_TASKS:             "FILL_TASKS",
    CREATE_TASK:            "CREATE_TASK",
    REMOVE_TASK:            "REMOVE_TASK",
    SET_TASK_NEW_MESSAGE:   "SET_TASK_NEW_MESSAGE",
    UPDATE_TASK:            "UPDATE_TASK",
    UNSET_COMPLETE_TASK:    "UNSET_COMPLETE_TASK",
    SET_FAVORITE_TASK:      "SET_FAVORITE_TASK",
    UNSET_FAVORITE_TASK:    "UNSET_FAVORITE_TASK",
    ENABLE_EDIT_STATE:      "ENABLE_EDIT_STATE",
    DISABLE_EDIT_STATE:     "DISABLE_EDIT_STATE",
    UPDATE_TASK_MESSAGE:    "UPDATE_TASK_MESSAGE",
    FILTER_TASK_BY_MESSAGE: "FILTER_TASK_BY_MESSAGE",
    COMPLETE_ALL_TASKS:     "COMPLETE_ALL_TASKS",

    // Async
    CREATE_TASK_ASYNC:         "CREATE_TASK_ASYNC",
    FETCH_TASKS_ASYNC:         "FETCH_TASKS_ASYNC",
    REMOVE_TASK_ASYNC:         "REMOVE_TASK_ASYNC",
    SET_COMPLETE_TASK_ASYNC:   "SET_COMPLETE_TASK_ASYNC",
    UNSET_COMPLETE_TASK_ASYNC: "UNSET_COMPLETE_TASK_ASYNC",
    SET_FAVORITE_TASK_ASYNC:   "SET_FAVORITE_TASK_ASYNC",
    UNSET_FAVORITE_TASK_ASYNC: "UNSET_FAVORITE_TASK_ASYNC",
    UPDATE_TASK_MESSAGE_ASYNC: "UPDATE_TASK_MESSAGE_ASYNC",
    CLEAR_TASK_NEW_MESSAGE:    "CLEAR_TASK_NEW_MESSAGE",
    COMPLETE_ALL_TASKS_ASYNC:  "COMPLETE_ALL_TASKS_ASYNC",
};
