export const types = {
    UPDATE_TASKS_FILTER:          "UPDATE_TASKS_FILTER",
    SET_ALL_TASKS_AS_COMPLETED:   "SET_ALL_TASKS_AS_COMPLETED",
    UNSET_ALL_TASKS_AS_COMPLETED: "UNSET_ALL_TASKS_AS_COMPLETED",
    CHECK_IS_ALL_TASKS_COMPLETED: "CHECK_IS_ALL_TASKS_COMPLETED",
};
